# Generated by Django 5.2.1 on 2025-07-07 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
