# Generated by Django 5.2.1 on 2025-07-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_pickuplocation_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuplocation',
            name='datetime',
        ),
    ]
