# Generated by Django 5.2.1 on 2025-07-06 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('location', '0001_initial'),
        ('payment', '0001_initial'),
        ('pickups', '0001_initial'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='payment_confirmed',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.collectorassignment'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.pickuplocation'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan'),
        ),
    ]
