# Generated by Django 5.2.1 on 2025-07-08 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_remove_pickuprequest_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
