# Generated by Django 5.2.1 on 2025-07-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_trashcollectorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcollectorprofile',
            old_name='collector',
            new_name='user',
        ),
    ]
